[options]
addons_path = C:/creyox_odoo/odoo_demo_19/odoo/addons,C:/creyox_odoo/odoo_demo_19/custom_addons
db_host = localhost
db_port = 5432
db_user = odoo_19
db_password = odoo19
http_port = 8086
admin_passwd = $pbkdf2-sha512$600000$2ru3dk7pfa.Vcm5NKeU8Jw$a8tfmLm.czske6GMnTZQW.L3y5x74Z3bovwqzpbbauJUgsOwjAe39WU/JwmjJtheJRmN9QdiIWSAlKsKCnJlCA